# Generated by Django 5.2.7 on 2025-10-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audittrail',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='audittrail',
            name='severity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
