# Generated by Django 5.2.7 on 2025-10-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_alter_audittrail_category_alter_audittrail_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, default='General', max_length=100),
        ),
    ]
