# Generated by Django 5.2.7 on 2025-10-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='recipe',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
