# Generated by Django 5.2.7 on 2025-10-21 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_item_recipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
    ]
