# Generated by Django 5.2.7 on 2025-10-22 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_item_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='supplier',
        ),
    ]
