# Generated by Django 5.2.7 on 2025-11-13 03:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_order_discount_order_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='ingredient_type',
            field=models.CharField(choices=[('non-perishable', 'Non-Perishable'), ('perishable', 'Perishable')], default='non-perishable', max_length=20, verbose_name='Perishable Type'),
        ),
        migrations.CreateModel(
            name='WastedLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=100)),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('cost_at_waste', models.DecimalField(decimal_places=2, help_text='The total cost of the wasted items', max_digits=10)),
                ('wasted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.CharField(choices=[('End-of-day spoilage', 'End-of-day spoilage'), ('Manual Entry - Spoilage', 'Manual Entry - Spoilage'), ('Manual Entry - Error', 'Manual Entry - Error'), ('Manual Entry - Other', 'Manual Entry - Other')], default='Manual Entry - Other', max_length=100)),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.ingredient')),
                ('user', models.ForeignKey(help_text='User who recorded the waste', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-wasted_at'],
            },
        ),
    ]
