# Generated by Django 5.2.8 on 2025-11-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0013_order_dining_option"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="inventorytransaction",
            new_name="pos_invento_created_2a04ce_idx",
            old_name="pos_invento_created_7f8c9d_idx",
        ),
        migrations.RenameIndex(
            model_name="inventorytransaction",
            new_name="pos_invento_ingredi_5d1c1b_idx",
            old_name="pos_invento_ingredi_a1b2c3_idx",
        ),
        migrations.RenameIndex(
            model_name="inventorytransaction",
            new_name="pos_invento_transac_44b55d_idx",
            old_name="pos_invento_transac_d4e5f6_idx",
        ),
        migrations.AddField(
            model_name="order",
            name="reference_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
