# Generated by Django 5.2.7 on 2025-12-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0015_add_soft_delete_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_buy1take1',
            field=models.BooleanField(default=False, verbose_name='Buy 1 Take 1 Promo'),
        ),
    ]
